### PR TITLE
Frame mode, usability and documentation

### PR DESCRIPTION
**Pull request by hsidd1**

### CODE REVIEW

**Comment by hsidd1** [comment]
@lincampbell So instead of only adding 1010 TLV type, I made it so that 1020 also appears but washed out (most recent commit). From this I was able to validate a couple of things, which would not be easy to confirm until we get accurate data from the next test run done in the lab. Currently, theres actually no points showing up at all within the gate, let alone just 1010s. Blue and Red denote clustering etc, while no Green or yellow appear (for frame mode). I agree we should look into the format of the radar output and then see if new data can be visualized accurately

**Comment by lincampbell** [comment]
I reviewed the readData_IWR6843 and it looks OK, data should be in the correct xyz etc. format, so must be a transformation/config error somewhere. Can you confirm for me the orientation of the radars in the physical gate? 

radar orientation

**Comment by lincampbell** [comment]
Can you also confirm that the radars are mounted on the correct side of the gate aisles? Radar should always be to the right when entering the gate aisles.


RAdar positioning

**Comment by hsidd1** [comment]
Good catch. I'll ask Arta to adjust it before the next run

**Comment by hsidd1** [comment]
Also might need to adjust the camera positioning. While x, y and scale factor for points can be configured, tilting them can be tricky and this seems to have a slight tilt to it compared to what's seen in Controlled test.avi

**Review by lincampbell — CHANGES_REQUESTED** [review]
Adjust physical set-up (camera tilt/radar position) & test with new recording to confirm that it's just a data recording issue. Otherwise, changes look OK

**Comment by lincampbell** [comment]
Do you know if the camera has been configured to record with the wide angle as well? At the current height (3m?) we should be getting much more of the environment in frame [below is screen cap of a previous test from 3m with the 90deg preset]. 
mcmaster_lab - frame at 0m2s

**Review by lincampbell — APPROVED** [review]

**Comment by hsidd1** [comment]
@artaalikhani

**Pull request merged**
