### PR TITLE
With dbscan clustering

### PR DESCRIPTION
**Pull request by lincampbell**
NEW:
removed duplicated function in rta2_cv2visual.py; starting at line 167
created radar_clustering.py and ClusterProcessor Class
created obj_height and cluster_bbox functions
draw_clustered_points updated --> can show object center and highlight points used to calc the cluster

BUGS:
points_for_clustering not working as intended, each radar frame contains points for only 1 sensor at a time so the clustering isn't actually using all available points. Need to either reformat how it's used in main or just delete bc combining points used for display works well. See line 297 in rta2_cv2visual.py for the fix.

MISC
pls draw bbox around cluster area using values from new function. Also verify that it is giving the right bbox output and attach obj height above bbox

### CODE REVIEW

**Comment by hfyxin** [comment]
Agree that `points_for_clustering` is not a good source of data. I modified it slightly such that the clustering uses **static points for display**. This ensures what you see is what you get. The downside is some additional computation.

For @hsidd1, a few things for you to take on:
- I changed the way how points are removed from the gate area (in order to use the result for clustering). but it doesn't work properly. Please investigate. It may be related to the rectangle area values.
- Linnea produced bounding boxes (bbox) as a clustering output. Please add functions to draw those on the frame.
- Optional: the text display is not working. Try to fix it if you have time.

Also for all, please do not merge a pull request to main without my consent.

**Comment by lincampbell** [comment]
remove static points is working for me. Check the config file b/c I set the bool to False before you updated that function so that might be the issue

**Comment by lincampbell** [comment]
Edit: sorry not static points, "remove noise" is working.  the points outside the gate area are not being used when I am testing it now

**Comment by hsidd1** [comment]
Bounding box visualization, noise removal and text display is all set up now and added to the branch and PR. Currently there isn't any info on clustering details printed to the frame, except for cluster object height printed on top of bounding boxes. If there's anything to display for clustering let me know and I can add it @lincampbell @hfyxin

**Comment by hfyxin** [comment]
Looks good to me. I'll merge the changes and remove this branch.

**Pull request merged**
